groups:
  - name: NoteAlerts
    rules:
      - alert: TooManyNotes
        expr: total_unprocessed_notes > 8
        for: 1m
        labels:
          severity: insane
        annotations:
          summary: "Too many unprocessed notes"
#       - alert: InstanceDownCritical
#         expr: up{job="services"} < 1
#         for: 1m
#         labels:
#           severity: high
#         annotations:
#           summary: "Alert with high severity."
